### ISSUE TITLE
NzxtKrakenPlugin could not initialize or has no sensors.

### ISSUE THREAD

**Issue by BlueTalon6** [brokenmass/Fancontrol.NzxtKraken#2]
I have an x53, FanControl 157 on Win 10. Tried all releases 1.3 - 1.0 and get the same error on all of them.
First error comes up on startup of FanControl, second error is spammed every second until I close FanControl.

```
21-May-23 2:26:29 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.NzxtKraken.NzxtKrakenX3.Update()
   at FanControl.NzxtKraken.NzxtKrakenPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
21-May-23 2:26:32 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.NzxtKraken.NzxtKrakenX3.Update()
   at FanControl.NzxtKraken.NzxtKrakenPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
21-May-23 2:26:33 PM: NzxtKrakenPlugin could not initialize or has no sensors.

21-May-23 2:26:35 PM: Unhandled exception in FanControl v157.0.0.0
21-May-23 2:26:35 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.NzxtKraken.NzxtKrakenX3.Update()
   at FanControl.NzxtKraken.NzxtKrakenPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by brokenmass** [comment]
Hi @BlueTalon6 : are you using the dotnet 4.8 version of fancontrol ?

**Comment by BlueTalon6** [comment]
4.8, have been updating since having installed 118 when there was no alternative. Switched to 7.0 but same error. 

Closing cam solved the error. Might be worth a comment in the readme for the less astute.

Thanks
